---
channel: stable
addons:
  mochad:
    repository: pascalrrr/mochad-ha-addon
    target: mochad
    image: ghcr.io/pascalrrr/mochad/{arch}
  hyperion:
    repository: pascalrrr/hyperion-ha-addon
    target: hyperion
    image: ghcr.io/pascalrrr/hyperion/{arch}
