---
channel: stable
addons:
  mochad:
    repository: floridaman7588/mochad-ha-addon
    target: mochad
    image: ghcr.io/floridaman7588/mochad/{arch}
  silabs-cfw:
    repository: floridaman7588/silabs-cfw-ha-addon
    target: silabs-cfw
    image: ghcr.io/floridaman7588/silabs-cfw/{arch}